/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        cyan: {
          50: "#F0FFFE",
          100: "#E1FFFD",
          200: "#C3FFFB",
          300: "#B6F2F1",
          400: "#9EEEED",
          500: "#7DE5E3",
          600: "#5CDBD9",
          700: "#4BB5B3",
          800: "#3A8E8C",
          900: "#2A6866",
        },
        lightGray: {
          50: "#FAFAFA",
          100: "#F5F5F5",
          200: "#EEEEEE",
          300: "#DFDDDF",
          400: "#BDBDBD",
          500: "#9E9E9E",
          600: "#757575",
          700: "#616161",
          800: "#424242",
          900: "#212121",
        },
        darkBlue: {
          50: "#F2F4F5",
          100: "#E5E9EB",
          200: "#CBD3D7",
          300: "#B1BDC3",
          400: "#97A7AF",
          500: "#7D919B",
          600: "#637B87",
          700: "#4B6570",
          800: "#223741",
          900: "#1A2B33",
        },
        grey: {
          50: "#F4F6F7",
          100: "#E9EDEF",
          200: "#D3DBDF",
          300: "#BDC9CF",
          400: "#A7B7BF",
          500: "#91A5AF",
          600: "#7B939F",
          700: "#65818F",
          800: "#4B7078",
          900: "#3A5860",
        },
        orange: {
          50: "#FEF7F0",
          100: "#FDEEE1",
          200: "#FBDDC3",
          300: "#F9CCA5",
          400: "#F7BB87",
          500: "#F5AA69",
          600: "#F3994B",
          700: "#F1962E",
          800: "#D17A1A",
          900: "#B15E06",
        },
      },
      animation: {
        "fade-in": "fadeIn 0.5s ease-in-out",
        "slide-up": "slideUp 0.5s ease-out",
        "slide-down": "slideDown 0.5s ease-out",
      },
      keyframes: {
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(100%)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        slideDown: {
          "0%": { transform: "translateY(-100%)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
